name: CI

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install autoconf automake build-essential fontconfig:i386 g++-multilib libcurl4-gnutls-dev:i386 libfontconfig1:i386 libfontconfig1-dev:i386 libfreetype-dev:i386 libncurses-dev:i386 libopenal-dev:i386 libopenal1:i386 libunwind-dev libunwind-dev:i386 libx11-dev:i386 mesa-common-dev:i386
      - name: Build
        run: ./build.sh
